
global:
  scrape_interval:     15s   
  evaluation_interval: 15s   

scrape_configs:

  - job_name: "alentapp-otel"
    static_configs:
      - targets: ["api:9464"]
        labels:
          app:     "alentapp"
          service: "api"
          env:     "production"


  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]